(|(| |9| |8| |7| |6| |5| |4| |3| |2| |1| |0| |)| $ - + / * E e .)
(expr exprp term termp fact float opt-sign opt-digits digits more-digits digit opt-exp exp eE opt-. floatp digitsp)
(
((- expr) (term exprp))
((|9| expr) (term exprp))
((|8| expr) (term exprp))
((|7| expr) (term exprp))
((|6| expr) (term exprp))
((|5| expr) (term exprp))
((|4| expr) (term exprp))
((|3| expr) (term exprp))
((|2| expr) (term exprp))
((|1| expr) (term exprp))
((|0| expr) (term exprp))
((. expr) (term exprp))
((+ expr) (term exprp))
((|(| expr) (term exprp))
((+ exprp) (+ term "ADD" exprp))
((- exprp) (- term "SUBTRACT" exprp))
((|)| exprp) ())
(($ exprp) ())
((- term) (fact termp))
((|9| term) (fact termp))
((|8| term) (fact termp))
((|7| term) (fact termp))
((|6| term) (fact termp))
((|5| term) (fact termp))
((|4| term) (fact termp))
((|3| term) (fact termp))
((|2| term) (fact termp))
((|1| term) (fact termp))
((|0| term) (fact termp))
((. term) (fact termp))
((+ term) (fact termp))
((|(| term) (fact termp))
((* termp) (* fact "MULTIPLY" termp))
((/ termp) (/ fact "DIVIDE" termp))
((|)| termp) ())
(($ termp) ())
((- termp) ())
((+ termp) ())
((|(| fact) (|(| expr |)|))
((|9| fact) (float "PUSH"))
((|8| fact) (float "PUSH"))
((|7| fact) (float "PUSH"))
((|6| fact) (float "PUSH"))
((|5| fact) (float "PUSH"))
((|4| fact) (float "PUSH"))
((|3| fact) (float "PUSH"))
((|2| fact) (float "PUSH"))
((|1| fact) (float "PUSH"))
((|0| fact) (float "PUSH"))
((. fact) (float "PUSH"))
((- fact) (float "PUSH"))
((+ fact) (float "PUSH"))
((- fact) (- fact "NEGATE"))
((|9| float) (opt-sign floatp))
((|8| float) (opt-sign floatp))
((|7| float) (opt-sign floatp))
((|6| float) (opt-sign floatp))
((|5| float) (opt-sign floatp))
((|4| float) (opt-sign floatp))
((|3| float) (opt-sign floatp))
((|2| float) (opt-sign floatp))
((|1| float) (opt-sign floatp))
((|0| float) (opt-sign floatp))
((. float) (opt-sign floatp))
((- float) (opt-sign floatp))
((+ float) (opt-sign floatp))
((+ opt-sign) ("POSITIVE" +))
((- opt-sign) ("NEGATIVE" -))
((|9| opt-sign) ())
((|8| opt-sign) ())
((|7| opt-sign) ())
((|6| opt-sign) ())
((|5| opt-sign) ())
((|4| opt-sign) ())
((|3| opt-sign) ())
((|2| opt-sign) ())
((|1| opt-sign) ())
((|0| opt-sign) ())
((. opt-sign) ())
((|9| opt-digits) (digits))
((|8| opt-digits) (digits))
((|7| opt-digits) (digits))
((|6| opt-digits) (digits))
((|5| opt-digits) (digits))
((|4| opt-digits) (digits))
((|3| opt-digits) (digits))
((|2| opt-digits) (digits))
((|1| opt-digits) (digits))
((|0| opt-digits) (digits))
((|)| opt-digits) ())
(($ opt-digits) ())
((- opt-digits) ())
((+ opt-digits) ())
((/ opt-digits) ())
((* opt-digits) ())
((E opt-digits) ())
((e opt-digits) ())
((|9| digits) ("ADD-DIGIT" digit digitsp))
((|8| digits) ("ADD-DIGIT" digit digitsp))
((|7| digits) ("ADD-DIGIT" digit digitsp))
((|6| digits) ("ADD-DIGIT" digit digitsp))
((|5| digits) ("ADD-DIGIT" digit digitsp))
((|4| digits) ("ADD-DIGIT" digit digitsp))
((|3| digits) ("ADD-DIGIT" digit digitsp))
((|2| digits) ("ADD-DIGIT" digit digitsp))
((|1| digits) ("ADD-DIGIT" digit digitsp))
((|0| digits) ("ADD-DIGIT" digit digitsp))
((|9| more-digits) ("ADD-DIGIT" digit more-digits))
((|8| more-digits) ("ADD-DIGIT" digit more-digits))
((|7| more-digits) ("ADD-DIGIT" digit more-digits))
((|6| more-digits) ("ADD-DIGIT" digit more-digits))
((|5| more-digits) ("ADD-DIGIT" digit more-digits))
((|4| more-digits) ("ADD-DIGIT" digit more-digits))
((|3| more-digits) ("ADD-DIGIT" digit more-digits))
((|2| more-digits) ("ADD-DIGIT" digit more-digits))
((|1| more-digits) ("ADD-DIGIT" digit more-digits))
((|0| more-digits) ("ADD-DIGIT" digit more-digits))
((|)| more-digits) ())
(($ more-digits) ())
((- more-digits) ())
((+ more-digits) ())
((/ more-digits) ())
((* more-digits) ())
((E more-digits) ())
((e more-digits) ())
((. more-digits) ())
((|0| digit) (|0|))
((|1| digit) (|1|))
((|2| digit) (|2|))
((|3| digit) (|3|))
((|4| digit) (|4|))
((|5| digit) (|5|))
((|6| digit) (|6|))
((|7| digit) (|7|))
((|8| digit) (|8|))
((|9| digit) (|9|))
((E opt-exp) ("EXP" exp))
((e opt-exp) ("EXP" exp))
((|)| opt-exp) ())
(($ opt-exp) ())
((- opt-exp) ())
((+ opt-exp) ())
((/ opt-exp) ())
((* opt-exp) ())
((E exp) (eE opt-sign "CLEAR" digits))
((e exp) (eE opt-sign "CLEAR" digits))
((e eE) (e))
((E eE) (E))
((. opt-.) (. "POINT" opt-digits))
((|)| opt-.) ())
(($ opt-.) ())
((- opt-.) ())
((+ opt-.) ())
((/ opt-.) ())
((* opt-.) ())
((E opt-.) ())
((e opt-.) ())
((. floatp) (. "CLEAR" "POINT" digits opt-exp))
((|9| floatp) ("CLEAR" digits opt-. opt-exp))
((|8| floatp) ("CLEAR" digits opt-. opt-exp))
((|7| floatp) ("CLEAR" digits opt-. opt-exp))
((|6| floatp) ("CLEAR" digits opt-. opt-exp))
((|5| floatp) ("CLEAR" digits opt-. opt-exp))
((|4| floatp) ("CLEAR" digits opt-. opt-exp))
((|3| floatp) ("CLEAR" digits opt-. opt-exp))
((|2| floatp) ("CLEAR" digits opt-. opt-exp))
((|1| floatp) ("CLEAR" digits opt-. opt-exp))
((|0| floatp) ("CLEAR" digits opt-. opt-exp))
((|)| digitsp) (more-digits))
(($ digitsp) (more-digits))
((- digitsp) (more-digits))
((+ digitsp) (more-digits))
((/ digitsp) (more-digits))
((* digitsp) (more-digits))
((E digitsp) (more-digits))
((e digitsp) (more-digits))
((. digitsp) (more-digits))
((|9| digitsp) (more-digits))
((|8| digitsp) (more-digits))
((|7| digitsp) (more-digits))
((|6| digitsp) (more-digits))
((|5| digitsp) (more-digits))
((|4| digitsp) (more-digits))
((|3| digitsp) (more-digits))
((|2| digitsp) (more-digits))
((|1| digitsp) (more-digits))
((|0| digitsp) (more-digits))
((|)| digitsp) ())
(($ digitsp) ())
((- digitsp) ())
((+ digitsp) ())
((/ digitsp) ())
((* digitsp) ())
((E digitsp) ())
((e digitsp) ())
((. digitsp) ())
)
