($ |(| |9| |8| |7| |6| |5| |4| |3| |2| |1| |0| |)| |\n| - + / *)
(lines expr exprp term termp fact int digits more-digits digit digitsp)
(
((+ lines) (expr "PRINT" |\n| lines))
((- lines) (expr "PRINT" |\n| lines))
((|9| lines) (expr "PRINT" |\n| lines))
((|8| lines) (expr "PRINT" |\n| lines))
((|7| lines) (expr "PRINT" |\n| lines))
((|6| lines) (expr "PRINT" |\n| lines))
((|5| lines) (expr "PRINT" |\n| lines))
((|4| lines) (expr "PRINT" |\n| lines))
((|3| lines) (expr "PRINT" |\n| lines))
((|2| lines) (expr "PRINT" |\n| lines))
((|1| lines) (expr "PRINT" |\n| lines))
((|0| lines) (expr "PRINT" |\n| lines))
((|(| lines) (expr "PRINT" |\n| lines))
(($ lines) ())
((+ expr) (term exprp))
((- expr) (term exprp))
((|9| expr) (term exprp))
((|8| expr) (term exprp))
((|7| expr) (term exprp))
((|6| expr) (term exprp))
((|5| expr) (term exprp))
((|4| expr) (term exprp))
((|3| expr) (term exprp))
((|2| expr) (term exprp))
((|1| expr) (term exprp))
((|0| expr) (term exprp))
((|(| expr) (term exprp))
((+ exprp) (+ term "ADD" exprp))
((- exprp) (- term "SUBTRACT" exprp))
((|)| exprp) ())
((|\n| exprp) ())
((+ term) (fact termp))
((- term) (fact termp))
((|9| term) (fact termp))
((|8| term) (fact termp))
((|7| term) (fact termp))
((|6| term) (fact termp))
((|5| term) (fact termp))
((|4| term) (fact termp))
((|3| term) (fact termp))
((|2| term) (fact termp))
((|1| term) (fact termp))
((|0| term) (fact termp))
((|(| term) (fact termp))
((* termp) (* fact "MULTIPLY" termp))
((/ termp) (/ fact "DIVIDE" termp))
((|)| termp) ())
((|\n| termp) ())
((- termp) ())
((+ termp) ())
((|(| fact) (|(| expr |)|))
((|9| fact) (int "PUSH"))
((|8| fact) (int "PUSH"))
((|7| fact) (int "PUSH"))
((|6| fact) (int "PUSH"))
((|5| fact) (int "PUSH"))
((|4| fact) (int "PUSH"))
((|3| fact) (int "PUSH"))
((|2| fact) (int "PUSH"))
((|1| fact) (int "PUSH"))
((|0| fact) (int "PUSH"))
((- fact) (- fact "NEGATE"))
((+ fact) (+ fact))
((|9| int) ("CLEAR" digits))
((|8| int) ("CLEAR" digits))
((|7| int) ("CLEAR" digits))
((|6| int) ("CLEAR" digits))
((|5| int) ("CLEAR" digits))
((|4| int) ("CLEAR" digits))
((|3| int) ("CLEAR" digits))
((|2| int) ("CLEAR" digits))
((|1| int) ("CLEAR" digits))
((|0| int) ("CLEAR" digits))
((|9| digits) ("ADD-DIGIT" digit digitsp))
((|8| digits) ("ADD-DIGIT" digit digitsp))
((|7| digits) ("ADD-DIGIT" digit digitsp))
((|6| digits) ("ADD-DIGIT" digit digitsp))
((|5| digits) ("ADD-DIGIT" digit digitsp))
((|4| digits) ("ADD-DIGIT" digit digitsp))
((|3| digits) ("ADD-DIGIT" digit digitsp))
((|2| digits) ("ADD-DIGIT" digit digitsp))
((|1| digits) ("ADD-DIGIT" digit digitsp))
((|0| digits) ("ADD-DIGIT" digit digitsp))
((|9| more-digits) ("ADD-DIGIT" digit more-digits))
((|8| more-digits) ("ADD-DIGIT" digit more-digits))
((|7| more-digits) ("ADD-DIGIT" digit more-digits))
((|6| more-digits) ("ADD-DIGIT" digit more-digits))
((|5| more-digits) ("ADD-DIGIT" digit more-digits))
((|4| more-digits) ("ADD-DIGIT" digit more-digits))
((|3| more-digits) ("ADD-DIGIT" digit more-digits))
((|2| more-digits) ("ADD-DIGIT" digit more-digits))
((|1| more-digits) ("ADD-DIGIT" digit more-digits))
((|0| more-digits) ("ADD-DIGIT" digit more-digits))
((|)| more-digits) ())
((|\n| more-digits) ())
((- more-digits) ())
((+ more-digits) ())
((/ more-digits) ())
((* more-digits) ())
((|0| digit) (|0|))
((|1| digit) (|1|))
((|2| digit) (|2|))
((|3| digit) (|3|))
((|4| digit) (|4|))
((|5| digit) (|5|))
((|6| digit) (|6|))
((|7| digit) (|7|))
((|8| digit) (|8|))
((|9| digit) (|9|))
((|)| digitsp) (more-digits))
((|\n| digitsp) (more-digits))
((- digitsp) (more-digits))
((+ digitsp) (more-digits))
((/ digitsp) (more-digits))
((* digitsp) (more-digits))
((|9| digitsp) (more-digits))
((|8| digitsp) (more-digits))
((|7| digitsp) (more-digits))
((|6| digitsp) (more-digits))
((|5| digitsp) (more-digits))
((|4| digitsp) (more-digits))
((|3| digitsp) (more-digits))
((|2| digitsp) (more-digits))
((|1| digitsp) (more-digits))
((|0| digitsp) (more-digits))
((|)| digitsp) ())
((|\n| digitsp) ())
((- digitsp) ())
((+ digitsp) ())
((/ digitsp) ())
((* digitsp) ())
)
