($ |9| |8| |7| |6| |5| |4| |3| |2| |1| |0| | | |\n| ! |"| |#| % & |'| |(| |)| * + , - . / : |;| < = > ? @ A B C D E F G H I J K L M N O P Q R S T U V W X Y Z |[| |\\| |]| ^ _ ` a b c d e f g h i j k l m n o p q r s t u v w x y z |{| |\|| |}| |~| \177)
(profile-file opt-header opt-whites opt-profiles profile profile-p callee caller class number name digits more-digits digit letters more-letters whites more-whites white letter)
(
(($ profile-file) (opt-whites opt-header opt-profiles))
((|9| profile-file) (opt-whites opt-header opt-profiles))
((|8| profile-file) (opt-whites opt-header opt-profiles))
((|7| profile-file) (opt-whites opt-header opt-profiles))
((|6| profile-file) (opt-whites opt-header opt-profiles))
((|5| profile-file) (opt-whites opt-header opt-profiles))
((|4| profile-file) (opt-whites opt-header opt-profiles))
((|3| profile-file) (opt-whites opt-header opt-profiles))
((|2| profile-file) (opt-whites opt-header opt-profiles))
((|1| profile-file) (opt-whites opt-header opt-profiles))
((|0| profile-file) (opt-whites opt-header opt-profiles))
((\177 profile-file) (opt-whites opt-header opt-profiles))
((|~| profile-file) (opt-whites opt-header opt-profiles))
((|}| profile-file) (opt-whites opt-header opt-profiles))
((|\|| profile-file) (opt-whites opt-header opt-profiles))
((|{| profile-file) (opt-whites opt-header opt-profiles))
((z profile-file) (opt-whites opt-header opt-profiles))
((y profile-file) (opt-whites opt-header opt-profiles))
((x profile-file) (opt-whites opt-header opt-profiles))
((w profile-file) (opt-whites opt-header opt-profiles))
((v profile-file) (opt-whites opt-header opt-profiles))
((u profile-file) (opt-whites opt-header opt-profiles))
((t profile-file) (opt-whites opt-header opt-profiles))
((s profile-file) (opt-whites opt-header opt-profiles))
((r profile-file) (opt-whites opt-header opt-profiles))
((q profile-file) (opt-whites opt-header opt-profiles))
((p profile-file) (opt-whites opt-header opt-profiles))
((o profile-file) (opt-whites opt-header opt-profiles))
((n profile-file) (opt-whites opt-header opt-profiles))
((m profile-file) (opt-whites opt-header opt-profiles))
((l profile-file) (opt-whites opt-header opt-profiles))
((k profile-file) (opt-whites opt-header opt-profiles))
((j profile-file) (opt-whites opt-header opt-profiles))
((i profile-file) (opt-whites opt-header opt-profiles))
((h profile-file) (opt-whites opt-header opt-profiles))
((g profile-file) (opt-whites opt-header opt-profiles))
((f profile-file) (opt-whites opt-header opt-profiles))
((e profile-file) (opt-whites opt-header opt-profiles))
((d profile-file) (opt-whites opt-header opt-profiles))
((c profile-file) (opt-whites opt-header opt-profiles))
((b profile-file) (opt-whites opt-header opt-profiles))
((a profile-file) (opt-whites opt-header opt-profiles))
((` profile-file) (opt-whites opt-header opt-profiles))
((_ profile-file) (opt-whites opt-header opt-profiles))
((^ profile-file) (opt-whites opt-header opt-profiles))
((|]| profile-file) (opt-whites opt-header opt-profiles))
((|\\| profile-file) (opt-whites opt-header opt-profiles))
((|[| profile-file) (opt-whites opt-header opt-profiles))
((Z profile-file) (opt-whites opt-header opt-profiles))
((Y profile-file) (opt-whites opt-header opt-profiles))
((X profile-file) (opt-whites opt-header opt-profiles))
((W profile-file) (opt-whites opt-header opt-profiles))
((V profile-file) (opt-whites opt-header opt-profiles))
((U profile-file) (opt-whites opt-header opt-profiles))
((T profile-file) (opt-whites opt-header opt-profiles))
((S profile-file) (opt-whites opt-header opt-profiles))
((R profile-file) (opt-whites opt-header opt-profiles))
((Q profile-file) (opt-whites opt-header opt-profiles))
((P profile-file) (opt-whites opt-header opt-profiles))
((O profile-file) (opt-whites opt-header opt-profiles))
((N profile-file) (opt-whites opt-header opt-profiles))
((M profile-file) (opt-whites opt-header opt-profiles))
((L profile-file) (opt-whites opt-header opt-profiles))
((K profile-file) (opt-whites opt-header opt-profiles))
((J profile-file) (opt-whites opt-header opt-profiles))
((I profile-file) (opt-whites opt-header opt-profiles))
((H profile-file) (opt-whites opt-header opt-profiles))
((G profile-file) (opt-whites opt-header opt-profiles))
((F profile-file) (opt-whites opt-header opt-profiles))
((E profile-file) (opt-whites opt-header opt-profiles))
((D profile-file) (opt-whites opt-header opt-profiles))
((C profile-file) (opt-whites opt-header opt-profiles))
((B profile-file) (opt-whites opt-header opt-profiles))
((A profile-file) (opt-whites opt-header opt-profiles))
((@ profile-file) (opt-whites opt-header opt-profiles))
((? profile-file) (opt-whites opt-header opt-profiles))
((> profile-file) (opt-whites opt-header opt-profiles))
((= profile-file) (opt-whites opt-header opt-profiles))
((< profile-file) (opt-whites opt-header opt-profiles))
((|;| profile-file) (opt-whites opt-header opt-profiles))
((: profile-file) (opt-whites opt-header opt-profiles))
((/ profile-file) (opt-whites opt-header opt-profiles))
((. profile-file) (opt-whites opt-header opt-profiles))
((- profile-file) (opt-whites opt-header opt-profiles))
((, profile-file) (opt-whites opt-header opt-profiles))
((+ profile-file) (opt-whites opt-header opt-profiles))
((* profile-file) (opt-whites opt-header opt-profiles))
((|)| profile-file) (opt-whites opt-header opt-profiles))
((|(| profile-file) (opt-whites opt-header opt-profiles))
((|'| profile-file) (opt-whites opt-header opt-profiles))
((& profile-file) (opt-whites opt-header opt-profiles))
((% profile-file) (opt-whites opt-header opt-profiles))
((|#| profile-file) (opt-whites opt-header opt-profiles))
((|"| profile-file) (opt-whites opt-header opt-profiles))
((! profile-file) (opt-whites opt-header opt-profiles))
((|\n| profile-file) (opt-whites opt-header opt-profiles))
((| | profile-file) (opt-whites opt-header opt-profiles))
((\177 opt-header) (name name name))
((|~| opt-header) (name name name))
((|}| opt-header) (name name name))
((|\|| opt-header) (name name name))
((|{| opt-header) (name name name))
((z opt-header) (name name name))
((y opt-header) (name name name))
((x opt-header) (name name name))
((w opt-header) (name name name))
((v opt-header) (name name name))
((u opt-header) (name name name))
((t opt-header) (name name name))
((s opt-header) (name name name))
((r opt-header) (name name name))
((q opt-header) (name name name))
((p opt-header) (name name name))
((o opt-header) (name name name))
((n opt-header) (name name name))
((m opt-header) (name name name))
((l opt-header) (name name name))
((k opt-header) (name name name))
((j opt-header) (name name name))
((i opt-header) (name name name))
((h opt-header) (name name name))
((g opt-header) (name name name))
((f opt-header) (name name name))
((e opt-header) (name name name))
((d opt-header) (name name name))
((c opt-header) (name name name))
((b opt-header) (name name name))
((a opt-header) (name name name))
((` opt-header) (name name name))
((_ opt-header) (name name name))
((^ opt-header) (name name name))
((|]| opt-header) (name name name))
((|\\| opt-header) (name name name))
((|[| opt-header) (name name name))
((Z opt-header) (name name name))
((Y opt-header) (name name name))
((X opt-header) (name name name))
((W opt-header) (name name name))
((V opt-header) (name name name))
((U opt-header) (name name name))
((T opt-header) (name name name))
((S opt-header) (name name name))
((R opt-header) (name name name))
((Q opt-header) (name name name))
((P opt-header) (name name name))
((O opt-header) (name name name))
((N opt-header) (name name name))
((M opt-header) (name name name))
((L opt-header) (name name name))
((K opt-header) (name name name))
((J opt-header) (name name name))
((I opt-header) (name name name))
((H opt-header) (name name name))
((G opt-header) (name name name))
((F opt-header) (name name name))
((E opt-header) (name name name))
((D opt-header) (name name name))
((C opt-header) (name name name))
((B opt-header) (name name name))
((A opt-header) (name name name))
((@ opt-header) (name name name))
((? opt-header) (name name name))
((> opt-header) (name name name))
((= opt-header) (name name name))
((< opt-header) (name name name))
((|;| opt-header) (name name name))
((: opt-header) (name name name))
((/ opt-header) (name name name))
((. opt-header) (name name name))
((- opt-header) (name name name))
((, opt-header) (name name name))
((+ opt-header) (name name name))
((* opt-header) (name name name))
((|)| opt-header) (name name name))
((|(| opt-header) (name name name))
((|'| opt-header) (name name name))
((& opt-header) (name name name))
((% opt-header) (name name name))
((|#| opt-header) (name name name))
((|"| opt-header) (name name name))
((! opt-header) (name name name))
(($ opt-header) ())
((|9| opt-header) ())
((|8| opt-header) ())
((|7| opt-header) ())
((|6| opt-header) ())
((|5| opt-header) ())
((|4| opt-header) ())
((|3| opt-header) ())
((|2| opt-header) ())
((|1| opt-header) ())
((|0| opt-header) ())
((|\n| opt-whites) (whites))
((| | opt-whites) (whites))
(($ opt-whites) ())
((|9| opt-whites) ())
((|8| opt-whites) ())
((|7| opt-whites) ())
((|6| opt-whites) ())
((|5| opt-whites) ())
((|4| opt-whites) ())
((|3| opt-whites) ())
((|2| opt-whites) ())
((|1| opt-whites) ())
((|0| opt-whites) ())
((\177 opt-whites) ())
((|~| opt-whites) ())
((|}| opt-whites) ())
((|\|| opt-whites) ())
((|{| opt-whites) ())
((z opt-whites) ())
((y opt-whites) ())
((x opt-whites) ())
((w opt-whites) ())
((v opt-whites) ())
((u opt-whites) ())
((t opt-whites) ())
((s opt-whites) ())
((r opt-whites) ())
((q opt-whites) ())
((p opt-whites) ())
((o opt-whites) ())
((n opt-whites) ())
((m opt-whites) ())
((l opt-whites) ())
((k opt-whites) ())
((j opt-whites) ())
((i opt-whites) ())
((h opt-whites) ())
((g opt-whites) ())
((f opt-whites) ())
((e opt-whites) ())
((d opt-whites) ())
((c opt-whites) ())
((b opt-whites) ())
((a opt-whites) ())
((` opt-whites) ())
((_ opt-whites) ())
((^ opt-whites) ())
((|]| opt-whites) ())
((|\\| opt-whites) ())
((|[| opt-whites) ())
((Z opt-whites) ())
((Y opt-whites) ())
((X opt-whites) ())
((W opt-whites) ())
((V opt-whites) ())
((U opt-whites) ())
((T opt-whites) ())
((S opt-whites) ())
((R opt-whites) ())
((Q opt-whites) ())
((P opt-whites) ())
((O opt-whites) ())
((N opt-whites) ())
((M opt-whites) ())
((L opt-whites) ())
((K opt-whites) ())
((J opt-whites) ())
((I opt-whites) ())
((H opt-whites) ())
((G opt-whites) ())
((F opt-whites) ())
((E opt-whites) ())
((D opt-whites) ())
((C opt-whites) ())
((B opt-whites) ())
((A opt-whites) ())
((@ opt-whites) ())
((? opt-whites) ())
((> opt-whites) ())
((= opt-whites) ())
((< opt-whites) ())
((|;| opt-whites) ())
((: opt-whites) ())
((/ opt-whites) ())
((. opt-whites) ())
((- opt-whites) ())
((, opt-whites) ())
((+ opt-whites) ())
((* opt-whites) ())
((|)| opt-whites) ())
((|(| opt-whites) ())
((|'| opt-whites) ())
((& opt-whites) ())
((% opt-whites) ())
((|#| opt-whites) ())
((|"| opt-whites) ())
((! opt-whites) ())
((|9| opt-profiles) (profile opt-profiles))
((|8| opt-profiles) (profile opt-profiles))
((|7| opt-profiles) (profile opt-profiles))
((|6| opt-profiles) (profile opt-profiles))
((|5| opt-profiles) (profile opt-profiles))
((|4| opt-profiles) (profile opt-profiles))
((|3| opt-profiles) (profile opt-profiles))
((|2| opt-profiles) (profile opt-profiles))
((|1| opt-profiles) (profile opt-profiles))
((|0| opt-profiles) (profile opt-profiles))
(($ opt-profiles) ())
((|9| profile) (number profile-p))
((|8| profile) (number profile-p))
((|7| profile) (number profile-p))
((|6| profile) (number profile-p))
((|5| profile) (number profile-p))
((|4| profile) (number profile-p))
((|3| profile) (number profile-p))
((|2| profile) (number profile-p))
((|1| profile) (number profile-p))
((|0| profile) (number profile-p))
((|9| profile-p) (callee))
((|8| profile-p) (callee))
((|7| profile-p) (callee))
((|6| profile-p) (callee))
((|5| profile-p) (callee))
((|4| profile-p) (callee))
((|3| profile-p) (callee))
((|2| profile-p) (callee))
((|1| profile-p) (callee))
((|0| profile-p) (callee))
((\177 profile-p) (caller))
((|~| profile-p) (caller))
((|}| profile-p) (caller))
((|\|| profile-p) (caller))
((|{| profile-p) (caller))
((z profile-p) (caller))
((y profile-p) (caller))
((x profile-p) (caller))
((w profile-p) (caller))
((v profile-p) (caller))
((u profile-p) (caller))
((t profile-p) (caller))
((s profile-p) (caller))
((r profile-p) (caller))
((q profile-p) (caller))
((p profile-p) (caller))
((o profile-p) (caller))
((n profile-p) (caller))
((m profile-p) (caller))
((l profile-p) (caller))
((k profile-p) (caller))
((j profile-p) (caller))
((i profile-p) (caller))
((h profile-p) (caller))
((g profile-p) (caller))
((f profile-p) (caller))
((e profile-p) (caller))
((d profile-p) (caller))
((c profile-p) (caller))
((b profile-p) (caller))
((a profile-p) (caller))
((` profile-p) (caller))
((_ profile-p) (caller))
((^ profile-p) (caller))
((|]| profile-p) (caller))
((|\\| profile-p) (caller))
((|[| profile-p) (caller))
((Z profile-p) (caller))
((Y profile-p) (caller))
((X profile-p) (caller))
((W profile-p) (caller))
((V profile-p) (caller))
((U profile-p) (caller))
((T profile-p) (caller))
((S profile-p) (caller))
((R profile-p) (caller))
((Q profile-p) (caller))
((P profile-p) (caller))
((O profile-p) (caller))
((N profile-p) (caller))
((M profile-p) (caller))
((L profile-p) (caller))
((K profile-p) (caller))
((J profile-p) (caller))
((I profile-p) (caller))
((H profile-p) (caller))
((G profile-p) (caller))
((F profile-p) (caller))
((E profile-p) (caller))
((D profile-p) (caller))
((C profile-p) (caller))
((B profile-p) (caller))
((A profile-p) (caller))
((@ profile-p) (caller))
((? profile-p) (caller))
((> profile-p) (caller))
((= profile-p) (caller))
((< profile-p) (caller))
((|;| profile-p) (caller))
((: profile-p) (caller))
((/ profile-p) (caller))
((. profile-p) (caller))
((- profile-p) (caller))
((, profile-p) (caller))
((+ profile-p) (caller))
((* profile-p) (caller))
((|)| profile-p) (caller))
((|(| profile-p) (caller))
((|'| profile-p) (caller))
((& profile-p) (caller))
((% profile-p) (caller))
((|#| profile-p) (caller))
((|"| profile-p) (caller))
((! profile-p) (caller))
((|9| callee) (number class name))
((|8| callee) (number class name))
((|7| callee) (number class name))
((|6| callee) (number class name))
((|5| callee) (number class name))
((|4| callee) (number class name))
((|3| callee) (number class name))
((|2| callee) (number class name))
((|1| callee) (number class name))
((|0| callee) (number class name))
((\177 caller) (name))
((|~| caller) (name))
((|}| caller) (name))
((|\|| caller) (name))
((|{| caller) (name))
((z caller) (name))
((y caller) (name))
((x caller) (name))
((w caller) (name))
((v caller) (name))
((u caller) (name))
((t caller) (name))
((s caller) (name))
((r caller) (name))
((q caller) (name))
((p caller) (name))
((o caller) (name))
((n caller) (name))
((m caller) (name))
((l caller) (name))
((k caller) (name))
((j caller) (name))
((i caller) (name))
((h caller) (name))
((g caller) (name))
((f caller) (name))
((e caller) (name))
((d caller) (name))
((c caller) (name))
((b caller) (name))
((a caller) (name))
((` caller) (name))
((_ caller) (name))
((^ caller) (name))
((|]| caller) (name))
((|\\| caller) (name))
((|[| caller) (name))
((Z caller) (name))
((Y caller) (name))
((X caller) (name))
((W caller) (name))
((V caller) (name))
((U caller) (name))
((T caller) (name))
((S caller) (name))
((R caller) (name))
((Q caller) (name))
((P caller) (name))
((O caller) (name))
((N caller) (name))
((M caller) (name))
((L caller) (name))
((K caller) (name))
((J caller) (name))
((I caller) (name))
((H caller) (name))
((G caller) (name))
((F caller) (name))
((E caller) (name))
((D caller) (name))
((C caller) (name))
((B caller) (name))
((A caller) (name))
((@ caller) (name))
((? caller) (name))
((> caller) (name))
((= caller) (name))
((< caller) (name))
((|;| caller) (name))
((: caller) (name))
((/ caller) (name))
((. caller) (name))
((- caller) (name))
((, caller) (name))
((+ caller) (name))
((* caller) (name))
((|)| caller) (name))
((|(| caller) (name))
((|'| caller) (name))
((& caller) (name))
((% caller) (name))
((|#| caller) (name))
((|"| caller) (name))
((! caller) (name))
((U class) (U whites))
((B class) (B whites))
((|9| number) ("CLEAR" digits "PUSH" whites))
((|8| number) ("CLEAR" digits "PUSH" whites))
((|7| number) ("CLEAR" digits "PUSH" whites))
((|6| number) ("CLEAR" digits "PUSH" whites))
((|5| number) ("CLEAR" digits "PUSH" whites))
((|4| number) ("CLEAR" digits "PUSH" whites))
((|3| number) ("CLEAR" digits "PUSH" whites))
((|2| number) ("CLEAR" digits "PUSH" whites))
((|1| number) ("CLEAR" digits "PUSH" whites))
((|0| number) ("CLEAR" digits "PUSH" whites))
((\177 name) ("START-NAME" letters "END-NAME" whites))
((|~| name) ("START-NAME" letters "END-NAME" whites))
((|}| name) ("START-NAME" letters "END-NAME" whites))
((|\|| name) ("START-NAME" letters "END-NAME" whites))
((|{| name) ("START-NAME" letters "END-NAME" whites))
((z name) ("START-NAME" letters "END-NAME" whites))
((y name) ("START-NAME" letters "END-NAME" whites))
((x name) ("START-NAME" letters "END-NAME" whites))
((w name) ("START-NAME" letters "END-NAME" whites))
((v name) ("START-NAME" letters "END-NAME" whites))
((u name) ("START-NAME" letters "END-NAME" whites))
((t name) ("START-NAME" letters "END-NAME" whites))
((s name) ("START-NAME" letters "END-NAME" whites))
((r name) ("START-NAME" letters "END-NAME" whites))
((q name) ("START-NAME" letters "END-NAME" whites))
((p name) ("START-NAME" letters "END-NAME" whites))
((o name) ("START-NAME" letters "END-NAME" whites))
((n name) ("START-NAME" letters "END-NAME" whites))
((m name) ("START-NAME" letters "END-NAME" whites))
((l name) ("START-NAME" letters "END-NAME" whites))
((k name) ("START-NAME" letters "END-NAME" whites))
((j name) ("START-NAME" letters "END-NAME" whites))
((i name) ("START-NAME" letters "END-NAME" whites))
((h name) ("START-NAME" letters "END-NAME" whites))
((g name) ("START-NAME" letters "END-NAME" whites))
((f name) ("START-NAME" letters "END-NAME" whites))
((e name) ("START-NAME" letters "END-NAME" whites))
((d name) ("START-NAME" letters "END-NAME" whites))
((c name) ("START-NAME" letters "END-NAME" whites))
((b name) ("START-NAME" letters "END-NAME" whites))
((a name) ("START-NAME" letters "END-NAME" whites))
((` name) ("START-NAME" letters "END-NAME" whites))
((_ name) ("START-NAME" letters "END-NAME" whites))
((^ name) ("START-NAME" letters "END-NAME" whites))
((|]| name) ("START-NAME" letters "END-NAME" whites))
((|\\| name) ("START-NAME" letters "END-NAME" whites))
((|[| name) ("START-NAME" letters "END-NAME" whites))
((Z name) ("START-NAME" letters "END-NAME" whites))
((Y name) ("START-NAME" letters "END-NAME" whites))
((X name) ("START-NAME" letters "END-NAME" whites))
((W name) ("START-NAME" letters "END-NAME" whites))
((V name) ("START-NAME" letters "END-NAME" whites))
((U name) ("START-NAME" letters "END-NAME" whites))
((T name) ("START-NAME" letters "END-NAME" whites))
((S name) ("START-NAME" letters "END-NAME" whites))
((R name) ("START-NAME" letters "END-NAME" whites))
((Q name) ("START-NAME" letters "END-NAME" whites))
((P name) ("START-NAME" letters "END-NAME" whites))
((O name) ("START-NAME" letters "END-NAME" whites))
((N name) ("START-NAME" letters "END-NAME" whites))
((M name) ("START-NAME" letters "END-NAME" whites))
((L name) ("START-NAME" letters "END-NAME" whites))
((K name) ("START-NAME" letters "END-NAME" whites))
((J name) ("START-NAME" letters "END-NAME" whites))
((I name) ("START-NAME" letters "END-NAME" whites))
((H name) ("START-NAME" letters "END-NAME" whites))
((G name) ("START-NAME" letters "END-NAME" whites))
((F name) ("START-NAME" letters "END-NAME" whites))
((E name) ("START-NAME" letters "END-NAME" whites))
((D name) ("START-NAME" letters "END-NAME" whites))
((C name) ("START-NAME" letters "END-NAME" whites))
((B name) ("START-NAME" letters "END-NAME" whites))
((A name) ("START-NAME" letters "END-NAME" whites))
((@ name) ("START-NAME" letters "END-NAME" whites))
((? name) ("START-NAME" letters "END-NAME" whites))
((> name) ("START-NAME" letters "END-NAME" whites))
((= name) ("START-NAME" letters "END-NAME" whites))
((< name) ("START-NAME" letters "END-NAME" whites))
((|;| name) ("START-NAME" letters "END-NAME" whites))
((: name) ("START-NAME" letters "END-NAME" whites))
((/ name) ("START-NAME" letters "END-NAME" whites))
((. name) ("START-NAME" letters "END-NAME" whites))
((- name) ("START-NAME" letters "END-NAME" whites))
((, name) ("START-NAME" letters "END-NAME" whites))
((+ name) ("START-NAME" letters "END-NAME" whites))
((* name) ("START-NAME" letters "END-NAME" whites))
((|)| name) ("START-NAME" letters "END-NAME" whites))
((|(| name) ("START-NAME" letters "END-NAME" whites))
((|'| name) ("START-NAME" letters "END-NAME" whites))
((& name) ("START-NAME" letters "END-NAME" whites))
((% name) ("START-NAME" letters "END-NAME" whites))
((|#| name) ("START-NAME" letters "END-NAME" whites))
((|"| name) ("START-NAME" letters "END-NAME" whites))
((! name) ("START-NAME" letters "END-NAME" whites))
((|9| digits) ("ADD-DIGIT" digit more-digits))
((|8| digits) ("ADD-DIGIT" digit more-digits))
((|7| digits) ("ADD-DIGIT" digit more-digits))
((|6| digits) ("ADD-DIGIT" digit more-digits))
((|5| digits) ("ADD-DIGIT" digit more-digits))
((|4| digits) ("ADD-DIGIT" digit more-digits))
((|3| digits) ("ADD-DIGIT" digit more-digits))
((|2| digits) ("ADD-DIGIT" digit more-digits))
((|1| digits) ("ADD-DIGIT" digit more-digits))
((|0| digits) ("ADD-DIGIT" digit more-digits))
((|9| more-digits) ("ADD-DIGIT" digit more-digits))
((|8| more-digits) ("ADD-DIGIT" digit more-digits))
((|7| more-digits) ("ADD-DIGIT" digit more-digits))
((|6| more-digits) ("ADD-DIGIT" digit more-digits))
((|5| more-digits) ("ADD-DIGIT" digit more-digits))
((|4| more-digits) ("ADD-DIGIT" digit more-digits))
((|3| more-digits) ("ADD-DIGIT" digit more-digits))
((|2| more-digits) ("ADD-DIGIT" digit more-digits))
((|1| more-digits) ("ADD-DIGIT" digit more-digits))
((|0| more-digits) ("ADD-DIGIT" digit more-digits))
((|\n| more-digits) ())
((| | more-digits) ())
((|0| digit) (|0|))
((|1| digit) (|1|))
((|2| digit) (|2|))
((|3| digit) (|3|))
((|4| digit) (|4|))
((|5| digit) (|5|))
((|6| digit) (|6|))
((|7| digit) (|7|))
((|8| digit) (|8|))
((|9| digit) (|9|))
((\177 letters) ("ADD-LETTER" letter more-letters))
((|~| letters) ("ADD-LETTER" letter more-letters))
((|}| letters) ("ADD-LETTER" letter more-letters))
((|\|| letters) ("ADD-LETTER" letter more-letters))
((|{| letters) ("ADD-LETTER" letter more-letters))
((z letters) ("ADD-LETTER" letter more-letters))
((y letters) ("ADD-LETTER" letter more-letters))
((x letters) ("ADD-LETTER" letter more-letters))
((w letters) ("ADD-LETTER" letter more-letters))
((v letters) ("ADD-LETTER" letter more-letters))
((u letters) ("ADD-LETTER" letter more-letters))
((t letters) ("ADD-LETTER" letter more-letters))
((s letters) ("ADD-LETTER" letter more-letters))
((r letters) ("ADD-LETTER" letter more-letters))
((q letters) ("ADD-LETTER" letter more-letters))
((p letters) ("ADD-LETTER" letter more-letters))
((o letters) ("ADD-LETTER" letter more-letters))
((n letters) ("ADD-LETTER" letter more-letters))
((m letters) ("ADD-LETTER" letter more-letters))
((l letters) ("ADD-LETTER" letter more-letters))
((k letters) ("ADD-LETTER" letter more-letters))
((j letters) ("ADD-LETTER" letter more-letters))
((i letters) ("ADD-LETTER" letter more-letters))
((h letters) ("ADD-LETTER" letter more-letters))
((g letters) ("ADD-LETTER" letter more-letters))
((f letters) ("ADD-LETTER" letter more-letters))
((e letters) ("ADD-LETTER" letter more-letters))
((d letters) ("ADD-LETTER" letter more-letters))
((c letters) ("ADD-LETTER" letter more-letters))
((b letters) ("ADD-LETTER" letter more-letters))
((a letters) ("ADD-LETTER" letter more-letters))
((` letters) ("ADD-LETTER" letter more-letters))
((_ letters) ("ADD-LETTER" letter more-letters))
((^ letters) ("ADD-LETTER" letter more-letters))
((|]| letters) ("ADD-LETTER" letter more-letters))
((|\\| letters) ("ADD-LETTER" letter more-letters))
((|[| letters) ("ADD-LETTER" letter more-letters))
((Z letters) ("ADD-LETTER" letter more-letters))
((Y letters) ("ADD-LETTER" letter more-letters))
((X letters) ("ADD-LETTER" letter more-letters))
((W letters) ("ADD-LETTER" letter more-letters))
((V letters) ("ADD-LETTER" letter more-letters))
((U letters) ("ADD-LETTER" letter more-letters))
((T letters) ("ADD-LETTER" letter more-letters))
((S letters) ("ADD-LETTER" letter more-letters))
((R letters) ("ADD-LETTER" letter more-letters))
((Q letters) ("ADD-LETTER" letter more-letters))
((P letters) ("ADD-LETTER" letter more-letters))
((O letters) ("ADD-LETTER" letter more-letters))
((N letters) ("ADD-LETTER" letter more-letters))
((M letters) ("ADD-LETTER" letter more-letters))
((L letters) ("ADD-LETTER" letter more-letters))
((K letters) ("ADD-LETTER" letter more-letters))
((J letters) ("ADD-LETTER" letter more-letters))
((I letters) ("ADD-LETTER" letter more-letters))
((H letters) ("ADD-LETTER" letter more-letters))
((G letters) ("ADD-LETTER" letter more-letters))
((F letters) ("ADD-LETTER" letter more-letters))
((E letters) ("ADD-LETTER" letter more-letters))
((D letters) ("ADD-LETTER" letter more-letters))
((C letters) ("ADD-LETTER" letter more-letters))
((B letters) ("ADD-LETTER" letter more-letters))
((A letters) ("ADD-LETTER" letter more-letters))
((@ letters) ("ADD-LETTER" letter more-letters))
((? letters) ("ADD-LETTER" letter more-letters))
((> letters) ("ADD-LETTER" letter more-letters))
((= letters) ("ADD-LETTER" letter more-letters))
((< letters) ("ADD-LETTER" letter more-letters))
((|;| letters) ("ADD-LETTER" letter more-letters))
((: letters) ("ADD-LETTER" letter more-letters))
((/ letters) ("ADD-LETTER" letter more-letters))
((. letters) ("ADD-LETTER" letter more-letters))
((- letters) ("ADD-LETTER" letter more-letters))
((, letters) ("ADD-LETTER" letter more-letters))
((+ letters) ("ADD-LETTER" letter more-letters))
((* letters) ("ADD-LETTER" letter more-letters))
((|)| letters) ("ADD-LETTER" letter more-letters))
((|(| letters) ("ADD-LETTER" letter more-letters))
((|'| letters) ("ADD-LETTER" letter more-letters))
((& letters) ("ADD-LETTER" letter more-letters))
((% letters) ("ADD-LETTER" letter more-letters))
((|#| letters) ("ADD-LETTER" letter more-letters))
((|"| letters) ("ADD-LETTER" letter more-letters))
((! letters) ("ADD-LETTER" letter more-letters))
((\177 more-letters) ("ADD-LETTER" letter more-letters))
((|~| more-letters) ("ADD-LETTER" letter more-letters))
((|}| more-letters) ("ADD-LETTER" letter more-letters))
((|\|| more-letters) ("ADD-LETTER" letter more-letters))
((|{| more-letters) ("ADD-LETTER" letter more-letters))
((z more-letters) ("ADD-LETTER" letter more-letters))
((y more-letters) ("ADD-LETTER" letter more-letters))
((x more-letters) ("ADD-LETTER" letter more-letters))
((w more-letters) ("ADD-LETTER" letter more-letters))
((v more-letters) ("ADD-LETTER" letter more-letters))
((u more-letters) ("ADD-LETTER" letter more-letters))
((t more-letters) ("ADD-LETTER" letter more-letters))
((s more-letters) ("ADD-LETTER" letter more-letters))
((r more-letters) ("ADD-LETTER" letter more-letters))
((q more-letters) ("ADD-LETTER" letter more-letters))
((p more-letters) ("ADD-LETTER" letter more-letters))
((o more-letters) ("ADD-LETTER" letter more-letters))
((n more-letters) ("ADD-LETTER" letter more-letters))
((m more-letters) ("ADD-LETTER" letter more-letters))
((l more-letters) ("ADD-LETTER" letter more-letters))
((k more-letters) ("ADD-LETTER" letter more-letters))
((j more-letters) ("ADD-LETTER" letter more-letters))
((i more-letters) ("ADD-LETTER" letter more-letters))
((h more-letters) ("ADD-LETTER" letter more-letters))
((g more-letters) ("ADD-LETTER" letter more-letters))
((f more-letters) ("ADD-LETTER" letter more-letters))
((e more-letters) ("ADD-LETTER" letter more-letters))
((d more-letters) ("ADD-LETTER" letter more-letters))
((c more-letters) ("ADD-LETTER" letter more-letters))
((b more-letters) ("ADD-LETTER" letter more-letters))
((a more-letters) ("ADD-LETTER" letter more-letters))
((` more-letters) ("ADD-LETTER" letter more-letters))
((_ more-letters) ("ADD-LETTER" letter more-letters))
((^ more-letters) ("ADD-LETTER" letter more-letters))
((|]| more-letters) ("ADD-LETTER" letter more-letters))
((|\\| more-letters) ("ADD-LETTER" letter more-letters))
((|[| more-letters) ("ADD-LETTER" letter more-letters))
((Z more-letters) ("ADD-LETTER" letter more-letters))
((Y more-letters) ("ADD-LETTER" letter more-letters))
((X more-letters) ("ADD-LETTER" letter more-letters))
((W more-letters) ("ADD-LETTER" letter more-letters))
((V more-letters) ("ADD-LETTER" letter more-letters))
((U more-letters) ("ADD-LETTER" letter more-letters))
((T more-letters) ("ADD-LETTER" letter more-letters))
((S more-letters) ("ADD-LETTER" letter more-letters))
((R more-letters) ("ADD-LETTER" letter more-letters))
((Q more-letters) ("ADD-LETTER" letter more-letters))
((P more-letters) ("ADD-LETTER" letter more-letters))
((O more-letters) ("ADD-LETTER" letter more-letters))
((N more-letters) ("ADD-LETTER" letter more-letters))
((M more-letters) ("ADD-LETTER" letter more-letters))
((L more-letters) ("ADD-LETTER" letter more-letters))
((K more-letters) ("ADD-LETTER" letter more-letters))
((J more-letters) ("ADD-LETTER" letter more-letters))
((I more-letters) ("ADD-LETTER" letter more-letters))
((H more-letters) ("ADD-LETTER" letter more-letters))
((G more-letters) ("ADD-LETTER" letter more-letters))
((F more-letters) ("ADD-LETTER" letter more-letters))
((E more-letters) ("ADD-LETTER" letter more-letters))
((D more-letters) ("ADD-LETTER" letter more-letters))
((C more-letters) ("ADD-LETTER" letter more-letters))
((B more-letters) ("ADD-LETTER" letter more-letters))
((A more-letters) ("ADD-LETTER" letter more-letters))
((@ more-letters) ("ADD-LETTER" letter more-letters))
((? more-letters) ("ADD-LETTER" letter more-letters))
((> more-letters) ("ADD-LETTER" letter more-letters))
((= more-letters) ("ADD-LETTER" letter more-letters))
((< more-letters) ("ADD-LETTER" letter more-letters))
((|;| more-letters) ("ADD-LETTER" letter more-letters))
((: more-letters) ("ADD-LETTER" letter more-letters))
((/ more-letters) ("ADD-LETTER" letter more-letters))
((. more-letters) ("ADD-LETTER" letter more-letters))
((- more-letters) ("ADD-LETTER" letter more-letters))
((, more-letters) ("ADD-LETTER" letter more-letters))
((+ more-letters) ("ADD-LETTER" letter more-letters))
((* more-letters) ("ADD-LETTER" letter more-letters))
((|)| more-letters) ("ADD-LETTER" letter more-letters))
((|(| more-letters) ("ADD-LETTER" letter more-letters))
((|'| more-letters) ("ADD-LETTER" letter more-letters))
((& more-letters) ("ADD-LETTER" letter more-letters))
((% more-letters) ("ADD-LETTER" letter more-letters))
((|#| more-letters) ("ADD-LETTER" letter more-letters))
((|"| more-letters) ("ADD-LETTER" letter more-letters))
((! more-letters) ("ADD-LETTER" letter more-letters))
((|\n| more-letters) ())
((| | more-letters) ())
((|\n| whites) (white more-whites))
((| | whites) (white more-whites))
((|\n| more-whites) (white more-whites))
((| | more-whites) (white more-whites))
(($ more-whites) ())
((|9| more-whites) ())
((|8| more-whites) ())
((|7| more-whites) ())
((|6| more-whites) ())
((|5| more-whites) ())
((|4| more-whites) ())
((|3| more-whites) ())
((|2| more-whites) ())
((|1| more-whites) ())
((|0| more-whites) ())
((\177 more-whites) ())
((|~| more-whites) ())
((|}| more-whites) ())
((|\|| more-whites) ())
((|{| more-whites) ())
((z more-whites) ())
((y more-whites) ())
((x more-whites) ())
((w more-whites) ())
((v more-whites) ())
((u more-whites) ())
((t more-whites) ())
((s more-whites) ())
((r more-whites) ())
((q more-whites) ())
((p more-whites) ())
((o more-whites) ())
((n more-whites) ())
((m more-whites) ())
((l more-whites) ())
((k more-whites) ())
((j more-whites) ())
((i more-whites) ())
((h more-whites) ())
((g more-whites) ())
((f more-whites) ())
((e more-whites) ())
((d more-whites) ())
((c more-whites) ())
((b more-whites) ())
((a more-whites) ())
((` more-whites) ())
((_ more-whites) ())
((^ more-whites) ())
((|]| more-whites) ())
((|\\| more-whites) ())
((|[| more-whites) ())
((Z more-whites) ())
((Y more-whites) ())
((X more-whites) ())
((W more-whites) ())
((V more-whites) ())
((U more-whites) ())
((T more-whites) ())
((S more-whites) ())
((R more-whites) ())
((Q more-whites) ())
((P more-whites) ())
((O more-whites) ())
((N more-whites) ())
((M more-whites) ())
((L more-whites) ())
((K more-whites) ())
((J more-whites) ())
((I more-whites) ())
((H more-whites) ())
((G more-whites) ())
((F more-whites) ())
((E more-whites) ())
((D more-whites) ())
((C more-whites) ())
((B more-whites) ())
((A more-whites) ())
((@ more-whites) ())
((? more-whites) ())
((> more-whites) ())
((= more-whites) ())
((< more-whites) ())
((|;| more-whites) ())
((: more-whites) ())
((/ more-whites) ())
((. more-whites) ())
((- more-whites) ())
((, more-whites) ())
((+ more-whites) ())
((* more-whites) ())
((|)| more-whites) ())
((|(| more-whites) ())
((|'| more-whites) ())
((& more-whites) ())
((% more-whites) ())
((|#| more-whites) ())
((|"| more-whites) ())
((! more-whites) ())
((| | white) (| |))
((|\n| white) (|\n|))
((! letter) (!))
((|"| letter) (|"|))
((|#| letter) (|#|))
((% letter) (%))
((& letter) (&))
((|'| letter) (|'|))
((|(| letter) (|(|))
((|)| letter) (|)|))
((* letter) (*))
((+ letter) (+))
((, letter) (,))
((- letter) (-))
((. letter) (.))
((/ letter) (/))
((: letter) (:))
((|;| letter) (|;|))
((< letter) (<))
((= letter) (=))
((> letter) (>))
((? letter) (?))
((@ letter) (@))
((A letter) (A))
((B letter) (B))
((C letter) (C))
((D letter) (D))
((E letter) (E))
((F letter) (F))
((G letter) (G))
((H letter) (H))
((I letter) (I))
((J letter) (J))
((K letter) (K))
((L letter) (L))
((M letter) (M))
((N letter) (N))
((O letter) (O))
((P letter) (P))
((Q letter) (Q))
((R letter) (R))
((S letter) (S))
((T letter) (T))
((U letter) (U))
((V letter) (V))
((W letter) (W))
((X letter) (X))
((Y letter) (Y))
((Z letter) (Z))
((|[| letter) (|[|))
((|\\| letter) (|\\|))
((|]| letter) (|]|))
((^ letter) (^))
((_ letter) (_))
((` letter) (`))
((a letter) (a))
((b letter) (b))
((c letter) (c))
((d letter) (d))
((e letter) (e))
((f letter) (f))
((g letter) (g))
((h letter) (h))
((i letter) (i))
((j letter) (j))
((k letter) (k))
((l letter) (l))
((m letter) (m))
((n letter) (n))
((o letter) (o))
((p letter) (p))
((q letter) (q))
((r letter) (r))
((s letter) (s))
((t letter) (t))
((u letter) (u))
((v letter) (v))
((w letter) (w))
((x letter) (x))
((y letter) (y))
((z letter) (z))
((|{| letter) (|{|))
((|\|| letter) (|\||))
((|}| letter) (|}|))
((|~| letter) (|~|))
((\177 letter) (\177))
)
