(|\013| \035 |\n| \033 \037 \177 |~| |}| |\|| |{| z y x w v u t s r q p o n m l k j i h g f e d c b a ` ? > = < |;| : |9| |8| |7| |6| |5| |4| |3| |2| |1| |0| / . - , + * |)| |(| |'| & % $ |#| |"| ! | | _ ^ |]| |\\| |[| Z Y X W V U T S R Q P O N M L K J I H G F E D C B A @)
(alpha graph exit-graph line move draws draw coord HIADDR LOY LOX printable graphp coordp coordpp)
(
((\177 alpha) (printable "PRINT" alpha))
((|~| alpha) (printable "PRINT" alpha))
((|}| alpha) (printable "PRINT" alpha))
((|\|| alpha) (printable "PRINT" alpha))
((|{| alpha) (printable "PRINT" alpha))
((z alpha) (printable "PRINT" alpha))
((y alpha) (printable "PRINT" alpha))
((x alpha) (printable "PRINT" alpha))
((w alpha) (printable "PRINT" alpha))
((v alpha) (printable "PRINT" alpha))
((u alpha) (printable "PRINT" alpha))
((t alpha) (printable "PRINT" alpha))
((s alpha) (printable "PRINT" alpha))
((r alpha) (printable "PRINT" alpha))
((q alpha) (printable "PRINT" alpha))
((p alpha) (printable "PRINT" alpha))
((o alpha) (printable "PRINT" alpha))
((n alpha) (printable "PRINT" alpha))
((m alpha) (printable "PRINT" alpha))
((l alpha) (printable "PRINT" alpha))
((k alpha) (printable "PRINT" alpha))
((j alpha) (printable "PRINT" alpha))
((i alpha) (printable "PRINT" alpha))
((h alpha) (printable "PRINT" alpha))
((g alpha) (printable "PRINT" alpha))
((f alpha) (printable "PRINT" alpha))
((e alpha) (printable "PRINT" alpha))
((d alpha) (printable "PRINT" alpha))
((c alpha) (printable "PRINT" alpha))
((b alpha) (printable "PRINT" alpha))
((a alpha) (printable "PRINT" alpha))
((` alpha) (printable "PRINT" alpha))
((_ alpha) (printable "PRINT" alpha))
((^ alpha) (printable "PRINT" alpha))
((|]| alpha) (printable "PRINT" alpha))
((|\\| alpha) (printable "PRINT" alpha))
((|[| alpha) (printable "PRINT" alpha))
((Z alpha) (printable "PRINT" alpha))
((Y alpha) (printable "PRINT" alpha))
((X alpha) (printable "PRINT" alpha))
((W alpha) (printable "PRINT" alpha))
((V alpha) (printable "PRINT" alpha))
((U alpha) (printable "PRINT" alpha))
((T alpha) (printable "PRINT" alpha))
((S alpha) (printable "PRINT" alpha))
((R alpha) (printable "PRINT" alpha))
((Q alpha) (printable "PRINT" alpha))
((P alpha) (printable "PRINT" alpha))
((O alpha) (printable "PRINT" alpha))
((N alpha) (printable "PRINT" alpha))
((M alpha) (printable "PRINT" alpha))
((L alpha) (printable "PRINT" alpha))
((K alpha) (printable "PRINT" alpha))
((J alpha) (printable "PRINT" alpha))
((I alpha) (printable "PRINT" alpha))
((H alpha) (printable "PRINT" alpha))
((G alpha) (printable "PRINT" alpha))
((F alpha) (printable "PRINT" alpha))
((E alpha) (printable "PRINT" alpha))
((D alpha) (printable "PRINT" alpha))
((C alpha) (printable "PRINT" alpha))
((B alpha) (printable "PRINT" alpha))
((A alpha) (printable "PRINT" alpha))
((@ alpha) (printable "PRINT" alpha))
((? alpha) (printable "PRINT" alpha))
((> alpha) (printable "PRINT" alpha))
((= alpha) (printable "PRINT" alpha))
((< alpha) (printable "PRINT" alpha))
((|;| alpha) (printable "PRINT" alpha))
((: alpha) (printable "PRINT" alpha))
((|9| alpha) (printable "PRINT" alpha))
((|8| alpha) (printable "PRINT" alpha))
((|7| alpha) (printable "PRINT" alpha))
((|6| alpha) (printable "PRINT" alpha))
((|5| alpha) (printable "PRINT" alpha))
((|4| alpha) (printable "PRINT" alpha))
((|3| alpha) (printable "PRINT" alpha))
((|2| alpha) (printable "PRINT" alpha))
((|1| alpha) (printable "PRINT" alpha))
((|0| alpha) (printable "PRINT" alpha))
((/ alpha) (printable "PRINT" alpha))
((. alpha) (printable "PRINT" alpha))
((- alpha) (printable "PRINT" alpha))
((, alpha) (printable "PRINT" alpha))
((+ alpha) (printable "PRINT" alpha))
((* alpha) (printable "PRINT" alpha))
((|)| alpha) (printable "PRINT" alpha))
((|(| alpha) (printable "PRINT" alpha))
((|'| alpha) (printable "PRINT" alpha))
((& alpha) (printable "PRINT" alpha))
((% alpha) (printable "PRINT" alpha))
(($ alpha) (printable "PRINT" alpha))
((|#| alpha) (printable "PRINT" alpha))
((|"| alpha) (printable "PRINT" alpha))
((! alpha) (printable "PRINT" alpha))
((| | alpha) (printable "PRINT" alpha))
((\033 alpha) (\033 |\n| "CLEAR" alpha))
((|\n| alpha) (|\n| "CR" alpha))
((|\n| alpha) (|\n| "LF" alpha))
((|\n| alpha) (|\n| "HT" alpha))
((|\n| alpha) (|\n| "BS" alpha))
((|\013| alpha) (|\013| "VT" alpha))
((\035 alpha) (graph alpha))
((\035 graph) (\035 line graphp))
((\037 exit-graph) (\037))
((\033 exit-graph) (\033 |\n| "CLEAR"))
((|\n| exit-graph) (|\n| "CR"))
((_ line) (move draws))
((^ line) (move draws))
((|]| line) (move draws))
((|\\| line) (move draws))
((|[| line) (move draws))
((Z line) (move draws))
((Y line) (move draws))
((X line) (move draws))
((W line) (move draws))
((V line) (move draws))
((U line) (move draws))
((T line) (move draws))
((S line) (move draws))
((R line) (move draws))
((Q line) (move draws))
((P line) (move draws))
((O line) (move draws))
((N line) (move draws))
((M line) (move draws))
((L line) (move draws))
((K line) (move draws))
((J line) (move draws))
((I line) (move draws))
((H line) (move draws))
((G line) (move draws))
((F line) (move draws))
((E line) (move draws))
((D line) (move draws))
((C line) (move draws))
((B line) (move draws))
((A line) (move draws))
((@ line) (move draws))
((? line) (move draws))
((> line) (move draws))
((= line) (move draws))
((< line) (move draws))
((|;| line) (move draws))
((: line) (move draws))
((|9| line) (move draws))
((|8| line) (move draws))
((|7| line) (move draws))
((|6| line) (move draws))
((|5| line) (move draws))
((|4| line) (move draws))
((|3| line) (move draws))
((|2| line) (move draws))
((|1| line) (move draws))
((|0| line) (move draws))
((/ line) (move draws))
((. line) (move draws))
((- line) (move draws))
((, line) (move draws))
((+ line) (move draws))
((* line) (move draws))
((|)| line) (move draws))
((|(| line) (move draws))
((|'| line) (move draws))
((& line) (move draws))
((% line) (move draws))
(($ line) (move draws))
((|#| line) (move draws))
((|"| line) (move draws))
((! line) (move draws))
((| | line) (move draws))
((\177 line) (move draws))
((|~| line) (move draws))
((|}| line) (move draws))
((|\|| line) (move draws))
((|{| line) (move draws))
((z line) (move draws))
((y line) (move draws))
((x line) (move draws))
((w line) (move draws))
((v line) (move draws))
((u line) (move draws))
((t line) (move draws))
((s line) (move draws))
((r line) (move draws))
((q line) (move draws))
((p line) (move draws))
((o line) (move draws))
((n line) (move draws))
((m line) (move draws))
((l line) (move draws))
((k line) (move draws))
((j line) (move draws))
((i line) (move draws))
((h line) (move draws))
((g line) (move draws))
((f line) (move draws))
((e line) (move draws))
((d line) (move draws))
((c line) (move draws))
((b line) (move draws))
((a line) (move draws))
((` line) (move draws))
((|\n| line) ())
((\033 line) ())
((\037 line) ())
((\035 line) ())
((_ move) (coord "MOVE"))
((^ move) (coord "MOVE"))
((|]| move) (coord "MOVE"))
((|\\| move) (coord "MOVE"))
((|[| move) (coord "MOVE"))
((Z move) (coord "MOVE"))
((Y move) (coord "MOVE"))
((X move) (coord "MOVE"))
((W move) (coord "MOVE"))
((V move) (coord "MOVE"))
((U move) (coord "MOVE"))
((T move) (coord "MOVE"))
((S move) (coord "MOVE"))
((R move) (coord "MOVE"))
((Q move) (coord "MOVE"))
((P move) (coord "MOVE"))
((O move) (coord "MOVE"))
((N move) (coord "MOVE"))
((M move) (coord "MOVE"))
((L move) (coord "MOVE"))
((K move) (coord "MOVE"))
((J move) (coord "MOVE"))
((I move) (coord "MOVE"))
((H move) (coord "MOVE"))
((G move) (coord "MOVE"))
((F move) (coord "MOVE"))
((E move) (coord "MOVE"))
((D move) (coord "MOVE"))
((C move) (coord "MOVE"))
((B move) (coord "MOVE"))
((A move) (coord "MOVE"))
((@ move) (coord "MOVE"))
((? move) (coord "MOVE"))
((> move) (coord "MOVE"))
((= move) (coord "MOVE"))
((< move) (coord "MOVE"))
((|;| move) (coord "MOVE"))
((: move) (coord "MOVE"))
((|9| move) (coord "MOVE"))
((|8| move) (coord "MOVE"))
((|7| move) (coord "MOVE"))
((|6| move) (coord "MOVE"))
((|5| move) (coord "MOVE"))
((|4| move) (coord "MOVE"))
((|3| move) (coord "MOVE"))
((|2| move) (coord "MOVE"))
((|1| move) (coord "MOVE"))
((|0| move) (coord "MOVE"))
((/ move) (coord "MOVE"))
((. move) (coord "MOVE"))
((- move) (coord "MOVE"))
((, move) (coord "MOVE"))
((+ move) (coord "MOVE"))
((* move) (coord "MOVE"))
((|)| move) (coord "MOVE"))
((|(| move) (coord "MOVE"))
((|'| move) (coord "MOVE"))
((& move) (coord "MOVE"))
((% move) (coord "MOVE"))
(($ move) (coord "MOVE"))
((|#| move) (coord "MOVE"))
((|"| move) (coord "MOVE"))
((! move) (coord "MOVE"))
((| | move) (coord "MOVE"))
((\177 move) (coord "MOVE"))
((|~| move) (coord "MOVE"))
((|}| move) (coord "MOVE"))
((|\|| move) (coord "MOVE"))
((|{| move) (coord "MOVE"))
((z move) (coord "MOVE"))
((y move) (coord "MOVE"))
((x move) (coord "MOVE"))
((w move) (coord "MOVE"))
((v move) (coord "MOVE"))
((u move) (coord "MOVE"))
((t move) (coord "MOVE"))
((s move) (coord "MOVE"))
((r move) (coord "MOVE"))
((q move) (coord "MOVE"))
((p move) (coord "MOVE"))
((o move) (coord "MOVE"))
((n move) (coord "MOVE"))
((m move) (coord "MOVE"))
((l move) (coord "MOVE"))
((k move) (coord "MOVE"))
((j move) (coord "MOVE"))
((i move) (coord "MOVE"))
((h move) (coord "MOVE"))
((g move) (coord "MOVE"))
((f move) (coord "MOVE"))
((e move) (coord "MOVE"))
((d move) (coord "MOVE"))
((c move) (coord "MOVE"))
((b move) (coord "MOVE"))
((a move) (coord "MOVE"))
((` move) (coord "MOVE"))
((_ draws) (draw draws))
((^ draws) (draw draws))
((|]| draws) (draw draws))
((|\\| draws) (draw draws))
((|[| draws) (draw draws))
((Z draws) (draw draws))
((Y draws) (draw draws))
((X draws) (draw draws))
((W draws) (draw draws))
((V draws) (draw draws))
((U draws) (draw draws))
((T draws) (draw draws))
((S draws) (draw draws))
((R draws) (draw draws))
((Q draws) (draw draws))
((P draws) (draw draws))
((O draws) (draw draws))
((N draws) (draw draws))
((M draws) (draw draws))
((L draws) (draw draws))
((K draws) (draw draws))
((J draws) (draw draws))
((I draws) (draw draws))
((H draws) (draw draws))
((G draws) (draw draws))
((F draws) (draw draws))
((E draws) (draw draws))
((D draws) (draw draws))
((C draws) (draw draws))
((B draws) (draw draws))
((A draws) (draw draws))
((@ draws) (draw draws))
((? draws) (draw draws))
((> draws) (draw draws))
((= draws) (draw draws))
((< draws) (draw draws))
((|;| draws) (draw draws))
((: draws) (draw draws))
((|9| draws) (draw draws))
((|8| draws) (draw draws))
((|7| draws) (draw draws))
((|6| draws) (draw draws))
((|5| draws) (draw draws))
((|4| draws) (draw draws))
((|3| draws) (draw draws))
((|2| draws) (draw draws))
((|1| draws) (draw draws))
((|0| draws) (draw draws))
((/ draws) (draw draws))
((. draws) (draw draws))
((- draws) (draw draws))
((, draws) (draw draws))
((+ draws) (draw draws))
((* draws) (draw draws))
((|)| draws) (draw draws))
((|(| draws) (draw draws))
((|'| draws) (draw draws))
((& draws) (draw draws))
((% draws) (draw draws))
(($ draws) (draw draws))
((|#| draws) (draw draws))
((|"| draws) (draw draws))
((! draws) (draw draws))
((| | draws) (draw draws))
((\177 draws) (draw draws))
((|~| draws) (draw draws))
((|}| draws) (draw draws))
((|\|| draws) (draw draws))
((|{| draws) (draw draws))
((z draws) (draw draws))
((y draws) (draw draws))
((x draws) (draw draws))
((w draws) (draw draws))
((v draws) (draw draws))
((u draws) (draw draws))
((t draws) (draw draws))
((s draws) (draw draws))
((r draws) (draw draws))
((q draws) (draw draws))
((p draws) (draw draws))
((o draws) (draw draws))
((n draws) (draw draws))
((m draws) (draw draws))
((l draws) (draw draws))
((k draws) (draw draws))
((j draws) (draw draws))
((i draws) (draw draws))
((h draws) (draw draws))
((g draws) (draw draws))
((f draws) (draw draws))
((e draws) (draw draws))
((d draws) (draw draws))
((c draws) (draw draws))
((b draws) (draw draws))
((a draws) (draw draws))
((` draws) (draw draws))
((|\n| draws) ())
((\033 draws) ())
((\037 draws) ())
((\035 draws) ())
((_ draw) (coord "DRAW"))
((^ draw) (coord "DRAW"))
((|]| draw) (coord "DRAW"))
((|\\| draw) (coord "DRAW"))
((|[| draw) (coord "DRAW"))
((Z draw) (coord "DRAW"))
((Y draw) (coord "DRAW"))
((X draw) (coord "DRAW"))
((W draw) (coord "DRAW"))
((V draw) (coord "DRAW"))
((U draw) (coord "DRAW"))
((T draw) (coord "DRAW"))
((S draw) (coord "DRAW"))
((R draw) (coord "DRAW"))
((Q draw) (coord "DRAW"))
((P draw) (coord "DRAW"))
((O draw) (coord "DRAW"))
((N draw) (coord "DRAW"))
((M draw) (coord "DRAW"))
((L draw) (coord "DRAW"))
((K draw) (coord "DRAW"))
((J draw) (coord "DRAW"))
((I draw) (coord "DRAW"))
((H draw) (coord "DRAW"))
((G draw) (coord "DRAW"))
((F draw) (coord "DRAW"))
((E draw) (coord "DRAW"))
((D draw) (coord "DRAW"))
((C draw) (coord "DRAW"))
((B draw) (coord "DRAW"))
((A draw) (coord "DRAW"))
((@ draw) (coord "DRAW"))
((? draw) (coord "DRAW"))
((> draw) (coord "DRAW"))
((= draw) (coord "DRAW"))
((< draw) (coord "DRAW"))
((|;| draw) (coord "DRAW"))
((: draw) (coord "DRAW"))
((|9| draw) (coord "DRAW"))
((|8| draw) (coord "DRAW"))
((|7| draw) (coord "DRAW"))
((|6| draw) (coord "DRAW"))
((|5| draw) (coord "DRAW"))
((|4| draw) (coord "DRAW"))
((|3| draw) (coord "DRAW"))
((|2| draw) (coord "DRAW"))
((|1| draw) (coord "DRAW"))
((|0| draw) (coord "DRAW"))
((/ draw) (coord "DRAW"))
((. draw) (coord "DRAW"))
((- draw) (coord "DRAW"))
((, draw) (coord "DRAW"))
((+ draw) (coord "DRAW"))
((* draw) (coord "DRAW"))
((|)| draw) (coord "DRAW"))
((|(| draw) (coord "DRAW"))
((|'| draw) (coord "DRAW"))
((& draw) (coord "DRAW"))
((% draw) (coord "DRAW"))
(($ draw) (coord "DRAW"))
((|#| draw) (coord "DRAW"))
((|"| draw) (coord "DRAW"))
((! draw) (coord "DRAW"))
((| | draw) (coord "DRAW"))
((\177 draw) (coord "DRAW"))
((|~| draw) (coord "DRAW"))
((|}| draw) (coord "DRAW"))
((|\|| draw) (coord "DRAW"))
((|{| draw) (coord "DRAW"))
((z draw) (coord "DRAW"))
((y draw) (coord "DRAW"))
((x draw) (coord "DRAW"))
((w draw) (coord "DRAW"))
((v draw) (coord "DRAW"))
((u draw) (coord "DRAW"))
((t draw) (coord "DRAW"))
((s draw) (coord "DRAW"))
((r draw) (coord "DRAW"))
((q draw) (coord "DRAW"))
((p draw) (coord "DRAW"))
((o draw) (coord "DRAW"))
((n draw) (coord "DRAW"))
((m draw) (coord "DRAW"))
((l draw) (coord "DRAW"))
((k draw) (coord "DRAW"))
((j draw) (coord "DRAW"))
((i draw) (coord "DRAW"))
((h draw) (coord "DRAW"))
((g draw) (coord "DRAW"))
((f draw) (coord "DRAW"))
((e draw) (coord "DRAW"))
((d draw) (coord "DRAW"))
((c draw) (coord "DRAW"))
((b draw) (coord "DRAW"))
((a draw) (coord "DRAW"))
((` draw) (coord "DRAW"))
((\177 coord) (LOY coordpp))
((|~| coord) (LOY coordpp))
((|}| coord) (LOY coordpp))
((|\|| coord) (LOY coordpp))
((|{| coord) (LOY coordpp))
((z coord) (LOY coordpp))
((y coord) (LOY coordpp))
((x coord) (LOY coordpp))
((w coord) (LOY coordpp))
((v coord) (LOY coordpp))
((u coord) (LOY coordpp))
((t coord) (LOY coordpp))
((s coord) (LOY coordpp))
((r coord) (LOY coordpp))
((q coord) (LOY coordpp))
((p coord) (LOY coordpp))
((o coord) (LOY coordpp))
((n coord) (LOY coordpp))
((m coord) (LOY coordpp))
((l coord) (LOY coordpp))
((k coord) (LOY coordpp))
((j coord) (LOY coordpp))
((i coord) (LOY coordpp))
((h coord) (LOY coordpp))
((g coord) (LOY coordpp))
((f coord) (LOY coordpp))
((e coord) (LOY coordpp))
((d coord) (LOY coordpp))
((c coord) (LOY coordpp))
((b coord) (LOY coordpp))
((a coord) (LOY coordpp))
((` coord) (LOY coordpp))
((? coord) (HIADDR coordp))
((> coord) (HIADDR coordp))
((= coord) (HIADDR coordp))
((< coord) (HIADDR coordp))
((|;| coord) (HIADDR coordp))
((: coord) (HIADDR coordp))
((|9| coord) (HIADDR coordp))
((|8| coord) (HIADDR coordp))
((|7| coord) (HIADDR coordp))
((|6| coord) (HIADDR coordp))
((|5| coord) (HIADDR coordp))
((|4| coord) (HIADDR coordp))
((|3| coord) (HIADDR coordp))
((|2| coord) (HIADDR coordp))
((|1| coord) (HIADDR coordp))
((|0| coord) (HIADDR coordp))
((/ coord) (HIADDR coordp))
((. coord) (HIADDR coordp))
((- coord) (HIADDR coordp))
((, coord) (HIADDR coordp))
((+ coord) (HIADDR coordp))
((* coord) (HIADDR coordp))
((|)| coord) (HIADDR coordp))
((|(| coord) (HIADDR coordp))
((|'| coord) (HIADDR coordp))
((& coord) (HIADDR coordp))
((% coord) (HIADDR coordp))
(($ coord) (HIADDR coordp))
((|#| coord) (HIADDR coordp))
((|"| coord) (HIADDR coordp))
((! coord) (HIADDR coordp))
((| | coord) (HIADDR coordp))
((_ coord) (LOX "oneAddr"))
((^ coord) (LOX "oneAddr"))
((|]| coord) (LOX "oneAddr"))
((|\\| coord) (LOX "oneAddr"))
((|[| coord) (LOX "oneAddr"))
((Z coord) (LOX "oneAddr"))
((Y coord) (LOX "oneAddr"))
((X coord) (LOX "oneAddr"))
((W coord) (LOX "oneAddr"))
((V coord) (LOX "oneAddr"))
((U coord) (LOX "oneAddr"))
((T coord) (LOX "oneAddr"))
((S coord) (LOX "oneAddr"))
((R coord) (LOX "oneAddr"))
((Q coord) (LOX "oneAddr"))
((P coord) (LOX "oneAddr"))
((O coord) (LOX "oneAddr"))
((N coord) (LOX "oneAddr"))
((M coord) (LOX "oneAddr"))
((L coord) (LOX "oneAddr"))
((K coord) (LOX "oneAddr"))
((J coord) (LOX "oneAddr"))
((I coord) (LOX "oneAddr"))
((H coord) (LOX "oneAddr"))
((G coord) (LOX "oneAddr"))
((F coord) (LOX "oneAddr"))
((E coord) (LOX "oneAddr"))
((D coord) (LOX "oneAddr"))
((C coord) (LOX "oneAddr"))
((B coord) (LOX "oneAddr"))
((A coord) (LOX "oneAddr"))
((@ coord) (LOX "oneAddr"))
((| | HIADDR) (| |))
((! HIADDR) (!))
((|"| HIADDR) (|"|))
((|#| HIADDR) (|#|))
(($ HIADDR) ($))
((% HIADDR) (%))
((& HIADDR) (&))
((|'| HIADDR) (|'|))
((|(| HIADDR) (|(|))
((|)| HIADDR) (|)|))
((* HIADDR) (*))
((+ HIADDR) (+))
((, HIADDR) (,))
((- HIADDR) (-))
((. HIADDR) (.))
((/ HIADDR) (/))
((|0| HIADDR) (|0|))
((|1| HIADDR) (|1|))
((|2| HIADDR) (|2|))
((|3| HIADDR) (|3|))
((|4| HIADDR) (|4|))
((|5| HIADDR) (|5|))
((|6| HIADDR) (|6|))
((|7| HIADDR) (|7|))
((|8| HIADDR) (|8|))
((|9| HIADDR) (|9|))
((: HIADDR) (:))
((|;| HIADDR) (|;|))
((< HIADDR) (<))
((= HIADDR) (=))
((> HIADDR) (>))
((? HIADDR) (?))
((` LOY) (`))
((a LOY) (a))
((b LOY) (b))
((c LOY) (c))
((d LOY) (d))
((e LOY) (e))
((f LOY) (f))
((g LOY) (g))
((h LOY) (h))
((i LOY) (i))
((j LOY) (j))
((k LOY) (k))
((l LOY) (l))
((m LOY) (m))
((n LOY) (n))
((o LOY) (o))
((p LOY) (p))
((q LOY) (q))
((r LOY) (r))
((s LOY) (s))
((t LOY) (t))
((u LOY) (u))
((v LOY) (v))
((w LOY) (w))
((x LOY) (x))
((y LOY) (y))
((z LOY) (z))
((|{| LOY) (|{|))
((|\|| LOY) (|\||))
((|}| LOY) (|}|))
((|~| LOY) (|~|))
((\177 LOY) (\177))
((@ LOX) (@))
((A LOX) (A))
((B LOX) (B))
((C LOX) (C))
((D LOX) (D))
((E LOX) (E))
((F LOX) (F))
((G LOX) (G))
((H LOX) (H))
((I LOX) (I))
((J LOX) (J))
((K LOX) (K))
((L LOX) (L))
((M LOX) (M))
((N LOX) (N))
((O LOX) (O))
((P LOX) (P))
((Q LOX) (Q))
((R LOX) (R))
((S LOX) (S))
((T LOX) (T))
((U LOX) (U))
((V LOX) (V))
((W LOX) (W))
((X LOX) (X))
((Y LOX) (Y))
((Z LOX) (Z))
((|[| LOX) (|[|))
((|\\| LOX) (|\\|))
((|]| LOX) (|]|))
((^ LOX) (^))
((_ LOX) (_))
((| | printable) (| |))
((! printable) (!))
((|"| printable) (|"|))
((|#| printable) (|#|))
(($ printable) ($))
((% printable) (%))
((& printable) (&))
((|'| printable) (|'|))
((|(| printable) (|(|))
((|)| printable) (|)|))
((* printable) (*))
((+ printable) (+))
((, printable) (,))
((- printable) (-))
((. printable) (.))
((/ printable) (/))
((|0| printable) (|0|))
((|1| printable) (|1|))
((|2| printable) (|2|))
((|3| printable) (|3|))
((|4| printable) (|4|))
((|5| printable) (|5|))
((|6| printable) (|6|))
((|7| printable) (|7|))
((|8| printable) (|8|))
((|9| printable) (|9|))
((: printable) (:))
((|;| printable) (|;|))
((< printable) (<))
((= printable) (=))
((> printable) (>))
((? printable) (?))
((@ printable) (@))
((A printable) (A))
((B printable) (B))
((C printable) (C))
((D printable) (D))
((E printable) (E))
((F printable) (F))
((G printable) (G))
((H printable) (H))
((I printable) (I))
((J printable) (J))
((K printable) (K))
((L printable) (L))
((M printable) (M))
((N printable) (N))
((O printable) (O))
((P printable) (P))
((Q printable) (Q))
((R printable) (R))
((S printable) (S))
((T printable) (T))
((U printable) (U))
((V printable) (V))
((W printable) (W))
((X printable) (X))
((Y printable) (Y))
((Z printable) (Z))
((|[| printable) (|[|))
((|\\| printable) (|\\|))
((|]| printable) (|]|))
((^ printable) (^))
((_ printable) (_))
((` printable) (`))
((a printable) (a))
((b printable) (b))
((c printable) (c))
((d printable) (d))
((e printable) (e))
((f printable) (f))
((g printable) (g))
((h printable) (h))
((i printable) (i))
((j printable) (j))
((k printable) (k))
((l printable) (l))
((m printable) (m))
((n printable) (n))
((o printable) (o))
((p printable) (p))
((q printable) (q))
((r printable) (r))
((s printable) (s))
((t printable) (t))
((u printable) (u))
((v printable) (v))
((w printable) (w))
((x printable) (x))
((y printable) (y))
((z printable) (z))
((|{| printable) (|{|))
((|\|| printable) (|\||))
((|}| printable) (|}|))
((|~| printable) (|~|))
((\177 printable) (\177))
((\035 graphp) (graph))
((|\n| graphp) (exit-graph))
((\033 graphp) (exit-graph))
((\037 graphp) (exit-graph))
((\177 coordp) (LOY HIADDR LOX "fourAddr"))
((|~| coordp) (LOY HIADDR LOX "fourAddr"))
((|}| coordp) (LOY HIADDR LOX "fourAddr"))
((|\|| coordp) (LOY HIADDR LOX "fourAddr"))
((|{| coordp) (LOY HIADDR LOX "fourAddr"))
((z coordp) (LOY HIADDR LOX "fourAddr"))
((y coordp) (LOY HIADDR LOX "fourAddr"))
((x coordp) (LOY HIADDR LOX "fourAddr"))
((w coordp) (LOY HIADDR LOX "fourAddr"))
((v coordp) (LOY HIADDR LOX "fourAddr"))
((u coordp) (LOY HIADDR LOX "fourAddr"))
((t coordp) (LOY HIADDR LOX "fourAddr"))
((s coordp) (LOY HIADDR LOX "fourAddr"))
((r coordp) (LOY HIADDR LOX "fourAddr"))
((q coordp) (LOY HIADDR LOX "fourAddr"))
((p coordp) (LOY HIADDR LOX "fourAddr"))
((o coordp) (LOY HIADDR LOX "fourAddr"))
((n coordp) (LOY HIADDR LOX "fourAddr"))
((m coordp) (LOY HIADDR LOX "fourAddr"))
((l coordp) (LOY HIADDR LOX "fourAddr"))
((k coordp) (LOY HIADDR LOX "fourAddr"))
((j coordp) (LOY HIADDR LOX "fourAddr"))
((i coordp) (LOY HIADDR LOX "fourAddr"))
((h coordp) (LOY HIADDR LOX "fourAddr"))
((g coordp) (LOY HIADDR LOX "fourAddr"))
((f coordp) (LOY HIADDR LOX "fourAddr"))
((e coordp) (LOY HIADDR LOX "fourAddr"))
((d coordp) (LOY HIADDR LOX "fourAddr"))
((c coordp) (LOY HIADDR LOX "fourAddr"))
((b coordp) (LOY HIADDR LOX "fourAddr"))
((a coordp) (LOY HIADDR LOX "fourAddr"))
((` coordp) (LOY HIADDR LOX "fourAddr"))
((_ coordp) (LOX "twoAddr"))
((^ coordp) (LOX "twoAddr"))
((|]| coordp) (LOX "twoAddr"))
((|\\| coordp) (LOX "twoAddr"))
((|[| coordp) (LOX "twoAddr"))
((Z coordp) (LOX "twoAddr"))
((Y coordp) (LOX "twoAddr"))
((X coordp) (LOX "twoAddr"))
((W coordp) (LOX "twoAddr"))
((V coordp) (LOX "twoAddr"))
((U coordp) (LOX "twoAddr"))
((T coordp) (LOX "twoAddr"))
((S coordp) (LOX "twoAddr"))
((R coordp) (LOX "twoAddr"))
((Q coordp) (LOX "twoAddr"))
((P coordp) (LOX "twoAddr"))
((O coordp) (LOX "twoAddr"))
((N coordp) (LOX "twoAddr"))
((M coordp) (LOX "twoAddr"))
((L coordp) (LOX "twoAddr"))
((K coordp) (LOX "twoAddr"))
((J coordp) (LOX "twoAddr"))
((I coordp) (LOX "twoAddr"))
((H coordp) (LOX "twoAddr"))
((G coordp) (LOX "twoAddr"))
((F coordp) (LOX "twoAddr"))
((E coordp) (LOX "twoAddr"))
((D coordp) (LOX "twoAddr"))
((C coordp) (LOX "twoAddr"))
((B coordp) (LOX "twoAddr"))
((A coordp) (LOX "twoAddr"))
((@ coordp) (LOX "twoAddr"))
((? coordpp) (HIADDR LOX "threeAddr"))
((> coordpp) (HIADDR LOX "threeAddr"))
((= coordpp) (HIADDR LOX "threeAddr"))
((< coordpp) (HIADDR LOX "threeAddr"))
((|;| coordpp) (HIADDR LOX "threeAddr"))
((: coordpp) (HIADDR LOX "threeAddr"))
((|9| coordpp) (HIADDR LOX "threeAddr"))
((|8| coordpp) (HIADDR LOX "threeAddr"))
((|7| coordpp) (HIADDR LOX "threeAddr"))
((|6| coordpp) (HIADDR LOX "threeAddr"))
((|5| coordpp) (HIADDR LOX "threeAddr"))
((|4| coordpp) (HIADDR LOX "threeAddr"))
((|3| coordpp) (HIADDR LOX "threeAddr"))
((|2| coordpp) (HIADDR LOX "threeAddr"))
((|1| coordpp) (HIADDR LOX "threeAddr"))
((|0| coordpp) (HIADDR LOX "threeAddr"))
((/ coordpp) (HIADDR LOX "threeAddr"))
((. coordpp) (HIADDR LOX "threeAddr"))
((- coordpp) (HIADDR LOX "threeAddr"))
((, coordpp) (HIADDR LOX "threeAddr"))
((+ coordpp) (HIADDR LOX "threeAddr"))
((* coordpp) (HIADDR LOX "threeAddr"))
((|)| coordpp) (HIADDR LOX "threeAddr"))
((|(| coordpp) (HIADDR LOX "threeAddr"))
((|'| coordpp) (HIADDR LOX "threeAddr"))
((& coordpp) (HIADDR LOX "threeAddr"))
((% coordpp) (HIADDR LOX "threeAddr"))
(($ coordpp) (HIADDR LOX "threeAddr"))
((|#| coordpp) (HIADDR LOX "threeAddr"))
((|"| coordpp) (HIADDR LOX "threeAddr"))
((! coordpp) (HIADDR LOX "threeAddr"))
((| | coordpp) (HIADDR LOX "threeAddr"))
((_ coordpp) (LOX "loLoAddr"))
((^ coordpp) (LOX "loLoAddr"))
((|]| coordpp) (LOX "loLoAddr"))
((|\\| coordpp) (LOX "loLoAddr"))
((|[| coordpp) (LOX "loLoAddr"))
((Z coordpp) (LOX "loLoAddr"))
((Y coordpp) (LOX "loLoAddr"))
((X coordpp) (LOX "loLoAddr"))
((W coordpp) (LOX "loLoAddr"))
((V coordpp) (LOX "loLoAddr"))
((U coordpp) (LOX "loLoAddr"))
((T coordpp) (LOX "loLoAddr"))
((S coordpp) (LOX "loLoAddr"))
((R coordpp) (LOX "loLoAddr"))
((Q coordpp) (LOX "loLoAddr"))
((P coordpp) (LOX "loLoAddr"))
((O coordpp) (LOX "loLoAddr"))
((N coordpp) (LOX "loLoAddr"))
((M coordpp) (LOX "loLoAddr"))
((L coordpp) (LOX "loLoAddr"))
((K coordpp) (LOX "loLoAddr"))
((J coordpp) (LOX "loLoAddr"))
((I coordpp) (LOX "loLoAddr"))
((H coordpp) (LOX "loLoAddr"))
((G coordpp) (LOX "loLoAddr"))
((F coordpp) (LOX "loLoAddr"))
((E coordpp) (LOX "loLoAddr"))
((D coordpp) (LOX "loLoAddr"))
((C coordpp) (LOX "loLoAddr"))
((B coordpp) (LOX "loLoAddr"))
((A coordpp) (LOX "loLoAddr"))
((@ coordpp) (LOX "loLoAddr"))
)
